In [33]:
import os
base_path = "/home/mshlis/Projects/RIET/DynamicQuery"
os.chdir(base_path)

from dynamicquery import utils
import pandas as pd
import numpy as np
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torch

In [2]:
class Clef2021RerankedDataset(TensorDataset):
    def __init__(self, 
                 encode_fn, 
                 claims, 
                 tweets, 
                 connections,
                 claim_embeddings,
                 ranks):
        self.claim_embeddings = claim_embeddings
        self.ranks = ranks
        run_tweets = tweets.join(connections.set_index("tweet_id"), on="id", how="inner")
        run_tweets = run_tweets.join(claims.set_index("vclaim_id"), on="claim_id", how="inner")
        run_tweets = run_tweets[["tweet", "vclaim"]].reset_index()
        run_tweets["encoded_tweet"] = run_tweets.tweet.apply(encode_fn)
        self.claim_idx = [claims.vclaim.to_list().index(t_claim) for t_claim in run_tweets.vclaim.to_list()]
        self.data = run_tweets
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, index):
        Xt = self.data.encoded_tweet[index]
        Xt = (np.array(Xt["input_ids"]), np.array(Xt["attention_mask"]))
        Xe = self.claim_embeddings[self.ranks[index]]
        # Ye = self.claim_embeddings[self.claim_idx[index:index+1]]
        return (Xt, Xe)
    
    
def get_clef2021_reranked_dataloader(encode_fn, 
                            claims, 
                            tweets, 
                            connections, 
                            claim_embeddings,
                            ranks,
                            params={'batch_size':32, 'shuffle':True}):
    dataset = Clef2021RerankedDataset(encode_fn, 
                              claims, 
                              tweets, 
                              connections, 
                              claim_embeddings,
                              ranks)
    return DataLoader(dataset, **params)        

In [2]:
exp_path = "./experiments/candidate_selection/finetune_st5_large_claims_negs"
train_neg_path = os.path.join(exp_path, "ranks_train.npy")
dev_neg_path = os.path.join(exp_path, "ranks_dev.npy")
emb_path = os.path.join(exp_path, "claim_embs.npy")
tweet_emb_path = os.path.join(exp_path, "tweet_embs.npy")

In [36]:
import transformers
os.getcwd(), transformers.__version__

('/home/mshlis/Projects/RIET/DynamicQuery', '4.17.0')

In [4]:
neg_ids = np.load(train_neg_path)
dev_neg_ids = np.load(dev_neg_path)
neg_embs = np.load(emb_path)
tweet_embs = np.load(tweet_emb_path, allow_pickle=True)

In [5]:
neg_ids.shape, neg_embs.shape

((999, 13825), (13825, 768))

In [6]:
import extended_roberta as roberta
from transformers import AutoTokenizer
from functools import partial
import importlib
importlib.reload(roberta)

MAX_LENGTH = 192

model_str = "roberta-base"
model = roberta.ExtendedRobertaForExternalClassification.from_pretrained(model_str)
model.load_state_dict(torch.load("./experiments/cross_query_v1/base_rndm_large_neg/trained_model.pt"))
tokenizer = AutoTokenizer.from_pretrained(model_str)
tokenize = partial(tokenizer, **dict(
    truncation=True, 
    max_length=MAX_LENGTH, 
    padding="max_length", 
    return_attention_mask=True
))

Some weights of the model checkpoint at roberta-base were not used when initializing ExtendedRobertaForExternalClassification: ['lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing ExtendedRobertaForExternalClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ExtendedRobertaForExternalClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ExtendedRobertaForExternalClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.encoder.adapter_layer.0.bias', 'roberta.encoder.adapter_

In [7]:
# Claim Data
tweets, test_tweets = utils.get_tweets()
test_tweets = test_tweets[1:]
train_conns, dev_conns, test_conns = utils.get_qrels()
claims = utils.get_claims()

In [8]:
# (dev_neg_ids[:, 0] == claim_idx[:]).mean()

In [21]:
import dataloaders
importlib.reload(dataloaders)

BATCH_SIZE = 32

train_dl = dataloaders.get_clef2021_reranked_eval_dataloader(
    tokenize, 
    claims, 
    tweets, 
    train_conns,
    neg_embs,
    neg_ids[:,:5],
    tweet_embs[()]["train"],
    params={'batch_size':BATCH_SIZE, 'shuffle':False})

dev_dl = dataloaders.get_clef2021_reranked_eval_dataloader(
    tokenize, 
    claims, 
    tweets, 
    dev_conns,
    neg_embs,
    dev_neg_ids[:,:5],
    tweet_embs[()]["dev"],
    params={'batch_size':BATCH_SIZE, 'shuffle':False}) 

In [22]:
model.eval()

probits = []
for inputs, external_inputs in train_dl:
    inpt_dict = {
        "input_ids": inputs[0],
        "attention_mask": inputs[1],
        "extended_states": external_inputs,
    }
    with torch.no_grad():
        out = model(**inpt_dict)
        _probits = torch.nn.functional.softmax(out.logits[:,:-1], dim=-1)
    probits.append(_probits.detach().numpy())
    
probits = np.concatenate(probits, 0)

In [23]:
dev_probits = []
for inputs, external_inputs in dev_dl:
    inpt_dict = {
        "input_ids": inputs[0],
        "attention_mask": inputs[1],
        "extended_states": external_inputs
    }
    with torch.no_grad():
        out = model(**inpt_dict)
        _probits = torch.nn.functional.softmax(out.logits[:,:-1], dim=-1)
    dev_probits.append(_probits.detach().numpy())
    
dev_probits = np.concatenate(dev_probits, 0)

In [24]:
out.logits.shape

torch.Size([8, 6])

In [25]:
reranks = probits.argsort()[:,::-1]
dev_reranks = dev_probits.argsort()[:,::-1]

In [26]:
probits.shape

(999, 5)

In [27]:
[(reranks[i] == 0).mean() for i in range(5)]

[0.2, 0.2, 0.2, 0.2, 0.2]

In [28]:
reranks

array([[1, 3, 2, 0, 4],
       [0, 2, 1, 4, 3],
       [0, 3, 4, 2, 1],
       ...,
       [0, 3, 1, 4, 2],
       [0, 1, 3, 4, 2],
       [0, 2, 4, 3, 1]])

In [29]:
def get_idx(connections, claims, tweets):
    run_tweets = tweets.join(connections.set_index("tweet_id"), on="id", how="inner")
    run_tweets = run_tweets.join(claims.set_index("vclaim_id"), on="claim_id", how="inner")
    run_tweets = run_tweets[["tweet", "vclaim"]].reset_index()
    claim_idx = [claims.vclaim.to_list().index(t_claim) for t_claim in run_tweets.vclaim.to_list()]
    return run_tweets, claim_idx

def avg_prec(gold, rankings, n):
    is_rel = (np.array(rankings)[:n] == gold).astype(float)
    return (is_rel/np.arange(1,n+1)).sum()

def recall(gold, rankings, n):
    is_rel = (np.array(rankings)[:n] == gold).astype(float)
    return is_rel.sum()

def mean_avg_prec(golds, rankings, n):
    avg_precs = [avg_prec(gold, rlist, n) for gold, rlist in zip(golds, rankings)]
    return np.array(avg_precs).mean()

def mean_recall(golds, rankings, n):
    avg_precs = [recall(gold, rlist, n) for gold, rlist in zip(golds, rankings)]
    return np.array(avg_precs).mean()

def get_negative_ranks(ranks, gold):
    return [r for r in ranks if r!=gold]

def get_negative_ranks_arr(ranks, gold):
    n_ranks = [get_negative_ranks(r, g) for r,g in zip(ranks, claim_idx)]
    return np.array(n_ranks)

map_results = {}
map_recall_results = {}
save_ranks = False
for ptn in ["train", "dev"]:
    if ptn == "train":
        run_tweets, claim_idx = get_idx(train_conns, claims, tweets)
        ranks = np.array([ids[rerank] for ids, rerank in zip(neg_ids, reranks)])
    elif ptn == "dev":
        run_tweets, claim_idx = get_idx(dev_conns, claims, tweets)
        ranks = np.array([ids[rerank] for ids, rerank in zip(dev_neg_ids, dev_reranks)])
    elif ptn == "test":
        run_tweets, claim_idx = get_idx(test_conns, claims, test_tweets)

    if save_ranks:
        np.save(f"./experiments/finetune_st5_large_claims_negs/negative_embs_{ptn}.npy",
                get_negative_ranks_arr(ranks, claim_idx))
        np.save(f"./experiments/finetune_st5_large_claims_negs/ranks_{ptn}.npy",
                np.array(ranks))
    
    map_results[ptn] = []
    for n in [1,5]:
        map_results[ptn].append(mean_avg_prec(claim_idx, ranks, n))
        
    map_recall_results[ptn] = []
    for n in [1,5]:
        map_recall_results[ptn].append(mean_recall(claim_idx, ranks, n))

In [30]:
ranks[:10]

array([[ 9221,  1184,  6580,  2843, 13600],
       [ 9221,  5270,  3998,  4757,  3767],
       [ 7808, 12947,  4065,  6447,  6213],
       [ 1640,  5398,  4388,  8051, 13760],
       [ 1640, 13760,  8051,  6823,  5309],
       [10734,   874, 11060,  6134, 10195],
       [12609,  9611, 13229,  9380,   456],
       [10537,  3926,  1658,  6830,  4077],
       [ 9764,  1476,  6676,  9655,  1721],
       [  177,  1476,  3812,  9655,  9764]])

In [31]:
map_results

{'train': [0.953953953953954, 0.9584584584584585],
 'dev': [0.375, 0.6146666666666667]}

In [32]:
map_recall_results

{'train': [0.953953953953954, 0.9629629629629629], 'dev': [0.375, 0.975]}

In [30]:
.063 * len(dev_dl.dataset) / len(dev_dl) 

1.8

In [29]:
len(dev_dl)

7

In [17]:
ns = list(range(1,6))
sum([1/n for n in ns])

2.283333333333333

In [18]:
ns

[1, 2, 3, 4, 5]

In [20]:
mult = sum([1/n for n in ns]) / 5
vals = [.963, .975]
[mult*v for v in vals]

[0.43977, 0.44525]

In [55]:
k = 5
m = 200
A = np.stack([np.random.permutation(k) for _ in range(m)], 0)
bA = (A == 0).astype(int)
print(bA[:,0].mean())

0.21


array([2, 1, 0, 3, 4])